### PR TITLE
Unify docker-compose.yaml and remove un-needed stack.env file plus drop in replacments for postgres and redis and my own build of qBittorrent

### PR DESCRIPTION
**Pull request by eoghan2t9**
Change Postgres to Citus drop in replacement
https://www.citusdata.com/

Change Redis to drop in fully open source replacement KeyDB and enable 4 threads.
https://docs.keydb.dev/

Change qBittorrent to my own build of Linuxserver.io that already includes the qBittorrent.conf
https://github.com/eoghan2t9/docker-qbittorrent

### CODE REVIEW

**Comment by FunkeCoder23** [comment]
`stack.env` was purposefully used 1. because users don't have to mess with compose.yml directly and 2. because portainer stores variables in `stack.env` (which is why it's not just `.env`)
Moving all of the variables inside of the compose defeats these two points

**Comment by FunkeCoder23** [comment]
Can you elaborate the benefits of these replacements? 

Also, it seems odd to replace the lsio version with your version. configs are easy enough to add, why do we need your build?

**Comment by eoghan2t9** [comment]
It's more my OCD head I've looked at it like what's the point of having the stack.env file when it can be added the way I have done. It's like going to the sink and filling two glasses of water half full only to pour one into the other 😂. As for the custom build of qbittorrent again just pure ease of use go users could essentially run curl or wget against the raw link to the compose file and pipe it into docker to bring up the containers. Also they can simply copy and paste the full compose file into the links of portainer or whatever docker management gui they want.

I am also currently making an advanced compose file for users that want all the bells and whistles like gluetun and a postgres webui etc.

**Comment by FunkeCoder23** [comment]
@purple-emily I think you can close this

**Pull request closed without merging**
