### PR TITLE
Change postgres image to pgtuned and changed redis-stack to redis-stack-server

### PR DESCRIPTION
**Pull request by eoghan2t9**
Change postgres to esgn/pgtuned
PostgreSQL/PostGIS image including automatic optimization using pgtune

Change redis-stack to redis-stack-server if RedisInsight isn't being used for deployment and makes the downloaded image slightly smaller.

### CODE REVIEW

**Comment by iPromKnight** [comment]
Sorry I don't like the look of that image

We aren't using any gis features, and the project itself is marked as alpha stability: https://github.com/esgn/pgtuned

**Comment by eoghan2t9** [comment]
> Sorry I don't like the look of that image
> 
> We aren't using any gis features, and the project itself is marked as alpha stability: https://github.com/esgn/pgtuned

Yeah just seen that myself so reverted the changes

**Comment by eoghan2t9** [comment]
@iPromKnight added another commit with my own build of postgres with the tuned.sh script added and gis removed

**Comment by eoghan2t9** [comment]
Latest commits have the following 

Got rid of the stack.env file and hard coded everything in the docker-compose file.

Custom build of qBittorrent that has the qBittorrent.conf already added perfect for when deploying via portainer etc

**Pull request closed without merging**
